on: workflow_dispatch

name: Create a release

jobs:
  build:
    name: Create a release
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: make
        uses: ./.github/actions/build-sqljs
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com/
      - name: Publish to Github Packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: npm publish
